In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv("newsgroups_train.csv")
df

text  target       category
0     From: degroff@netcom.com (21012d)\nSubject: Re...       2      sci.space
1     From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
2     From: healta@saturn.wwc.edu (Tammy R Healy)\nS...       0    alt.atheism
3     From: capelli@vnet.IBM.COM (Ron Capelli)\nSubj...       1  comp.graphics
4     From: henry@zoo.toronto.edu (Henry Spencer)\nS...       2      sci.space
...                                                 ...     ...            ...
1652  From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
1653  From: renes@ecpdsharmony.cern.ch (Rene S. Dutc...       1  comp.graphics
1654  From: xrcjd@resolve.gsfc.nasa.gov (Charles J. ...       2      sci.space
1655  From: dietz@cs.rochester.edu (Paul Dietz)\nSub...       2      sci.space
1656  From: jhwitten@cs.ruu.nl (Jurriaan Wittenberg)...       2      sci.space

[1657 rows x 3 columns]

In [2]:
from sklearn.feature_extraction.text import  CountVectorizer
count_vect=CountVectorizer(max_features=1500)
vectors=count_vect.fit_transform(df.text)
vectors=vectors.toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [3]:
X=vectors
y=df.target

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (1657, 1500)
Shape of y: (1657,)


In [4]:
print("Target Labels:\n",df.target)

Target Labels:
 0       2
1       1
2       0
3       1
4       2
       ..
1652    1
1653    1
1654    2
1655    2
1656    2
Name: target, Length: 1657, dtype: int64


In [5]:
df.target.unique()

array([2, 1, 0])

In [6]:
#Prepare subset of categories: alt.atheism, com.graphics, sci.space.
categories=['alt.atheism','com.graphics','sci.space']
df_subset=df[df['category'].isin(categories)]
df_subset

text  target     category
0     From: degroff@netcom.com (21012d)\nSubject: Re...       2    sci.space
2     From: healta@saturn.wwc.edu (Tammy R Healy)\nS...       0  alt.atheism
4     From: henry@zoo.toronto.edu (Henry Spencer)\nS...       2    sci.space
5     From: dietz@cs.rochester.edu (Paul Dietz)\nSub...       2    sci.space
6     From: cobb@alexia.lis.uiuc.edu (Mike Cobb)\nSu...       0  alt.atheism
...                                                 ...     ...          ...
1649  From: 18084TM@msu.edu (Tom)\nSubject: Fred and...       2    sci.space
1650  From: kempmp@phoenix.oulu.fi (Petri Pihko)\nSu...       0  alt.atheism
1654  From: xrcjd@resolve.gsfc.nasa.gov (Charles J. ...       2    sci.space
1655  From: dietz@cs.rochester.edu (Paul Dietz)\nSub...       2    sci.space
1656  From: jhwitten@cs.ruu.nl (Jurriaan Wittenberg)...       2    sci.space

[1073 rows x 3 columns]

In [7]:
#train data
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score

clf=BernoulliNB()
clf.fit(X,y)

y_pred=clf.predict(X)
y_pred
print("BernoulliNB Accuracy:", accuracy_score(y, y_pred))

BernoulliNB Accuracy: 0.8859384429692215


In [8]:
#test data
df=pd.read_csv('newsgroups_test.csv')
df

text  target       category
0     From: mccall@mksol.dseg.ti.com (fred j mccall ...       2      sci.space
1     From: "Changyaw Wang" <wangc@cs.indiana.edu>\n...       1  comp.graphics
2     From: lioness@maple.circa.ufl.edu\nSubject: Te...       1  comp.graphics
3     From: hotopp@ami1.bwi.wec.com (Daniel T. Hotop...       1  comp.graphics
4     From: Ad-Robot@bobsbox.rent.com (Robotic Posti...       1  comp.graphics
...                                                 ...     ...            ...
1097  From: malek@pi.titech.ac.jp (Zidouri Abdelmale...       1  comp.graphics
1098  From: livesey@solntze.wpd.sgi.com (Jon Livesey...       0    alt.atheism
1099  From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...       0    alt.atheism
1100  From: beck@irzr17.inf.tu-dresden.de (Andre Bec...       1  comp.graphics
1101  From: 18084TM@msu.edu (Tom)\nSubject: Billboar...       2      sci.space

[1102 rows x 3 columns]

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectors=CountVectorizer(max_features=1500)
vectors=count_vectors.fit_transform(df.text)
vectors=vectors.toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [10]:
X_test=vectors
y_test=df.target

In [11]:
X_test.shape

(1102, 1500)

In [12]:
y_test.shape

(1102,)

In [20]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score
clf=BernoulliNB()
clf.fit(X_test,y_test)

y_pred=clf.predict(X_test)
y_pred

acc=accuracy_score(y_test,y_pred)
print("Accuracy Scorce:",acc)

Accuracy Scorce: 0.9147005444646098


In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
count_vectors=TfidfVectorizer(max_features=1500,stop_words='english')
vectors=count_vectors.fit_transform(df.text)
vectors=vectors.toarray()
vectors

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.09392888, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [31]:
X_test=vectors
y_test=df.target

In [32]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
clf=MultinomialNB()
clf.fit(X_test,y_test)

y_pred=clf.predict(X_test)
y_pred

acc=accuracy_score(y_test,y_pred)
print("Accuracy Scorce:",acc)

Accuracy Scorce: 0.9727767695099818
